environment:
  matrix:
    - node_version: "8"

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:node_version

test_script:
  - node ./scripts/make-appveyor-work.js
  - npm run setup

cache:
  - ./node_modules -> package.json

build: off
